"""add is_demo flag and ai_usage table

Hand-written, not autogenerated. Autogenerate compares models.py against the live
database, and the two have drifted in ways that do not matter (bare String in the
models vs VARCHAR(255) in the original DDL), so it would emit column-type rewrites
against production data alongside the two changes actually wanted here.

Both changes are additive and safe on a populated table:
  - users.is_demo has a server_default, so existing rows get false without a rewrite
    and without a NOT NULL violation.
  - ai_usage is a new table, so nothing existing is touched.

Revision ID: 1aec1c0c0ba4
Revises: ba3615f93ab6
Create Date: 2026-09-26 13:29:41.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '1aec1c0c0ba4'
down_revision: Union[str, Sequence[str], None] = 'ba3615f93ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "users",
        sa.Column("is_demo", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_table(
        "ai_usage",
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("usage_date", sa.Date(), primary_key=True),
        sa.Column("count", sa.Integer(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("ai_usage")
    op.drop_column("users", "is_demo")
